# application.yml
logging.pattern.level: DEBUG
spring:
  resources:
    static-locations: classpath:/webapp/
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  jpa:
    hibernate.ddl-auto: create
    show-sql: true
  freemarker:
    template-loader-path: classpath:/webapp/WEB-INF/
    cache: false
  output.ansi.enabled: always